# Permalinks
permalink:        pretty

# Setup
title:            RobotDotNet
tagline:          DotNet for the FIRST Robotics Competition (FRC)
url:              http://robotdotnet.github.io
paginate:         5
baseurl:          /

# Menu setup
menu:
    - ["Projects", "/projects/"]
    - ["Docs", "/docs/"]
    - ["Code", "https://github.com/robotdotnet"]
    - ["Community", "/community/"]
    - ["FAQ", "/faq/"]
    - ["About", "/about/"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/robotdotnet/robotdotnet.github.io